TOKEN = ''
DOMEN_VK = 'https://vk.com/'
API_VERSION = '5.131'
ABSENCE_MESSAGE = 'Информация отсутствует'
ACCESS_DENIED_MESSAGE = 'Доступ запрещён'
INCORRECT_REFERENCE_MESSAGE = 'Некорректная ссылка'
ERROR_MESSAGE = 'Непредвиденная ошибка'
RPS = 5
ACCESS_DENIED_CODE = 15
INCORRECT_REFERENCE_CODE = 100
